<?php $this->renderView('menus/_site'); ?>
<?php $b = $this->view->dados; $t = count($b) ?>
<div class="container">                    
    <section class="mt-5">        
        <div class="row d-flex align-items-center">
            <div class="col-lg-7">
                <img class="img-fluid rounded mb-3" src="<?= $this->helper->setPathImg($b[0]['title'], $b[0]['image'], 730, 400) ?>" alt="<?= $b[0]['title'] ?>">
                <a href="/article/show/<?= $this->helper->urlSEO($b[0]['title'], '-') ?>/<?= $b[0]['id'] ?>" class="mt-4 h2 text-dark"><?= $b[0]['title'] ?></a>
                <p class="mt-4"><?= $this->helper->resumir($b[0]['content'], 300) ?></p>
                <p class="text-muted text-end">                               
                    <i class="bi bi-journal-text"></i> <a href="<?= "/articles/category/" . $b[0]['caSlug'] ?>"><?= $b[0]['caName'] ?></a>
                </p>
            </div>
            <div class="col-lg-5">
                <ul class="list-unstyled">
                    <?php ($t > 5) ? $q = 5: $q = $t;
                    for ($y = 1; $y < $q; $y++):// 1, 2 e 3 $y <=5 layout correto ?>
                        <li class="row mb-4">
                            <a href="/article/show/<?= $this->helper->urlSEO($b[$y]['title'], '-') ?>/<?= $b[$y]['id'] ?>" class="col-3">
                                <img src="<?= $this->helper->setPathImg($b[$y]['title'], $b[$y]['image'], 300, 200) ?>" alt="<?= $b[$y]['title'] ?>" class="rounded img-fluid pt-1">
                            </a>
                            <div class="col-9">
                                <a href="/article/show/<?= $this->helper->urlSEO($b[$y]['title'], '-') ?>/<?= $b[$y]['id'] ?>">
                                    <h6 class="mb-3 h5 text-dark"><?= $b[$y]['title'] ?></h6>
                                </a>
                                <p><?= $this->helper->resumir($b[$y]['content'], 50) ?></p>
                                <span class="text-muted">                               
                                    <i class="bi bi-journal-text"></i> <a href="<?= "/articles/category/" . $b[$y]['caSlug'] ?>"><?= $b[$y]['caName'] ?></a>
                                </span>
                            </div>
                        </li>
                    <?php endfor;?>                      
                </ul>
            </div>
        </div>        
    </section>         
    <section>
        <div class="row mt-5 g-3">
            <?php if ($t <> $q);
            for ($z = 5; $z < $t; $z++)://for ($z = 6; $z <= 11; $z++): ?>
                <div class="col-lg-4 col-sm-6">
                    <div class="card h-100">
                        <a href="/article/show/<?= $this->helper->urlSEO($b[$z]['title'], '-') ?>/<?= $b[$z]['id'] ?>">
                            <img class="card-img-top" src="<?= $this->helper->setPathImg($b[$z]['title'], $b[$z]['image'], 700, 400) ?>" alt="<?= $b[$y]['title'] ?>">
                        </a>
                        <div class="card-body text-center">
                            <h4 class="card-title text-dark">
                                <a href="/article/show/<?= $this->helper->urlSEO($b[$z]['title'], '-') ?>/<?= $b[$z]['id'] ?>">
                                    <?= $b[$z]['title'] ?>
                                </a>
                            </h4>                            
                            <p class="card-text"><?= $this->helper->resumir($b[$z]['content'], 200) ?></p>
                        </div>
                    </div>
                </div>
            <?php endfor;?>            
        </div>
    </section>  

    <!-- Start pagination-->
<?php if ($this->view->contar > 1): ?>
    <?php
    $pAtual = $this->view->atual;
    $pTotal = $this->view->contar;
    $pMax = 2;
    $pUrl = "/articles?page=";
    ?>
    <ul class="pagination justify-content-center mt-3">
        <li class="page-item">
            <a class="page-link" href="<?= $pUrl ?>1"><i class="fa fa-step-backward"></i></a>
        </li>
        <?php for ($pBefore = $pAtual - $pMax; $pBefore <= $pAtual - 1; $pBefore++): ?>
            <?php if ($pBefore >= 1): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $pUrl . $pBefore ?>"><?= $pBefore ?></a>
                </li>
            <?php endif; ?>
        <?php endfor; ?>
        <li class="page-item active">
            <a class="page-link" href="#"><?= $pAtual ?></a>
        </li>
        <?php for ($pAfter = $pAtual + 1; $pAfter <= $pAtual + $pMax; $pAfter++): ?>
            <?php if ($pAfter <= $pTotal): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $pUrl . $pAfter ?>"><?= $pAfter ?></a>
                </li>
            <?php endif; ?>
        <?php endfor; ?>
        <li class="page-item">
            <a class="page-link" href="<?= $pUrl . $pTotal ?>"><i class="fa fa-step-forward"></i></a>
        </li>

    </ul>
<?php endif; ?>
<!-- End pagination -->   
    
</div>