
<!-- Page Content -->
<?php $this->renderView('menus/_site'); ?>
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="h2 my-3">
        <?= $this->getPageTitle() ?> |
        <small class="fs-5 text-info"><?= $this->view->dados[0]['caName'] ?></small>
        <?php //print_r($this->view->dados);?>
    </h1>
   
    <div class="row row-cols-1 row-cols-md-3 g-4 mb-3">
        <?php foreach ($this->view->dados as $d): ?> 
            <div class="col">
                <div class="card">
                    <img src="<?= $this->helper->setPathImg($d['title'], $d['image'], 900, 450) ?>" alt="<?= $d['title'] ?>" class="card-img-top">
                    <h5 class="card-title">
                        <div class="card-body">
                            <a href="/article/show/<?= $this->helper->urlSEO($d['title'], '-') ?>/<?= $d['id'] ?>">
                                <?= $d['title'] ?>      
                            </a>
                    </h5> 
                    <span class="text-muted text-end">                        
                        <i class="bi bi-pencil-square"></i> <?= $d['auName'] ?> |                                                     
                        <i class="bi bi-calendar2-week"></i> <?= date("F, Y", strtotime($d['created'])) ?>
                    </span>
                    <p class="card-text"> <?= $this->helper->resumir($d['content'], 200) ?></p>

                </div>
            </div> 
        <?php endforeach; ?>
    </div>
    <!-- Start pagination-->
    <?php if ($this->view->contar > 1): ?>
    <?php
    $pAtual = $this->view->atual;
    $pTotal = $this->view->contar;
    $pMax = 2;
    $pUrl = "/articles/category/".$d['caSlug']."?page=";
    ?>
    <ul class="pagination justify-content-center mt-3">
        <li class="page-item">
            <a class="page-link" href="<?= $pUrl ?>1"><i class="fa fa-step-backward"></i></a>
        </li>
        <?php for ($pBefore = $pAtual - $pMax; $pBefore <= $pAtual - 1; $pBefore++): ?>
            <?php if ($pBefore >= 1): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $pUrl . $pBefore ?>"><?= $pBefore ?></a>
                </li>
            <?php endif; ?>
        <?php endfor; ?>
        <li class="page-item active">
            <a class="page-link" href="#"><?= $pAtual ?></a>
        </li>
        <?php for ($pAfter = $pAtual + 1; $pAfter <= $pAtual + $pMax; $pAfter++): ?>
            <?php if ($pAfter <= $pTotal): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $pUrl . $pAfter ?>"><?= $pAfter ?></a>
                </li>
            <?php endif; ?>
        <?php endfor; ?>
        <li class="page-item">
            <a class="page-link" href="<?= $pUrl . $pTotal ?>"><i class="fa fa-step-forward"></i></a>
        </li>

    </ul>
<?php endif; ?>
<!-- End pagination --> 
</div>