<?php $this->renderView('menus/_admin_page');?>
<div class="container">
    <div class="row col-md-10 col-md-offset-1 custyle">
        <div class="page-header">
            <h2 class="card-title py-3">Visitors by IP</h2>
        </div>
        <?php if (!empty($this->view->visitor)): ?>
        <table class="table table-striped custab sortable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Id_title</th>
                    <th>IP</th>
                    <th>Acessed in</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->view->visitor as $vis): ?>
                <tr>
                    <td><?= $vis['viId'] ?></td>
                    <td><?= $vis['title'] ?></td>
                    <td><?= $vis['articles_id'] ?></td>
                    <td><?= $vis['ip'] ?></td>
                    <td><?= $vis['acessed_in'] ?></td>
                    <td class="text-center">
                        <a href="/admin/delete/visitor/<?= $vis['viId'] ?>" class="btn btn-danger btn-xs" onclick="confirm('Tem certeza que quer excluir?')"><span class="glyphicon glyphicon-remove"></span> Del</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php else: ?>
        <p>Não houve visitas!</p>
        <?php endif; ?>
        <!-- Start pagination-->
        <?php if ($this->view->contar > 1): ?>
        <?php
    $pAtual = $this->view->atual;
    $pTotal = $this->view->contar;
    $pMax = 2;
    $pUrl = "/admin/show/visitor?page=";
    ?>
        <ul class="pagination justify-content-center mt-3">
            <li class="page-item">
                <a class="page-link" href="<?=$pUrl?>1"><i class="fa fa-step-backward"></i></a>
            </li>
            <?php for($pBefore = $pAtual - $pMax; $pBefore <= $pAtual - 1;$pBefore++):?>
            <?php if($pBefore >=1):?>
            <li class="page-item">
                <a class="page-link" href="<?=$pUrl.$pBefore ?>"><?= $pBefore ?></a>
            </li>
            <?php endif;?>
            <?php endfor;?>
            <li class="page-item active">
                <a class="page-link" href="#"><?= $pAtual ?></a>
            </li>
            <?php for($pAfter = $pAtual + 1; $pAfter <= $pAtual + $pMax;$pAfter++):?>
            <?php if($pAfter <= $pTotal):?>
            <li class="page-item">
                <a class="page-link" href="<?= $pUrl.$pAfter ?>"><?= $pAfter ?></a>
            </li>
            <?php endif;?>
            <?php endfor;?>
            <li class="page-item">
                <a class="page-link" href="<?= $pUrl.$pTotal ?>"><i class="fa fa-step-forward"></i></a>
            </li>

        </ul>
        <?php endif; ?>
        <!-- End pagination -->

    </div>
</div>